corona3d_2020: Atmosphere.o Background_Species.o main.o Particle_CO.o Particle_CO2.o Particle_H.o Particle_N2.o Particle_O.o Particle.o Planet.o
	g++ Atmosphere.o Background_Species.o main.o Particle_CO.o Particle_CO2.o Particle_H.o Particle_N2.o Particle_O.o Particle.o Planet.o -o corona3d_2020
	
Atmosphere.o: Atmosphere.cpp
	g++ -c Atmosphere.cpp
	
Background_Species.o: Background_Species.cpp
	g++ -c Background_Species.cpp
	
main.o: main.cpp
	g++ -c main.cpp
	
Particle_CO.o: Particle_CO.cpp
	g++ -c Particle_CO.cpp
	
Particle_CO2.o: Particle_CO2.cpp
	g++ -c Particle_CO2.cpp
	
Particle_H.o: Particle_H.cpp
	g++ -c Particle_H.cpp
	
Particle_N2.o: Particle_N2.cpp
	g++ -c Particle_N2.cpp
	
Particle_O.o: Particle_O.cpp
	g++ -c Particle_O.cpp
	
Particle.o: Particle.cpp
	g++ -c Particle.cpp
	
Planet.o: Planet.cpp
	g++ -c Planet.cpp
	
clean:
	rm *.o corona3d_2020